<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountiesSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	*/
	public function run() {

		\DB::table('counties')->delete();

		$counties = [
			['county' => 'Bath and North East Somerset','country' => 'England'],
			['county' => 'Bedfordshire','country' => 'England'],
			['county' => 'Berkshire','country' => 'England'],
			['county' => 'Bristol','country' => 'England'],
			['county' => 'Buckinghamshire','country' => 'England'],
			['county' => 'Cambridgeshire','country' => 'England'],
			['county' => 'Cheshire','country' => 'England'],
			['county' => 'Cornwall','country' => 'England'],
			['county' => 'County Durham','country' => 'England'],
			['county' => 'Cumbria','country' => 'England'],
			['county' => 'Derbyshire','country' => 'England'],
			['county' => 'Devon','country' => 'England'],
			['county' => 'East Riding of Yorkshire','country' => 'England'],
			['county' => 'East Sussex','country' => 'England'],
			['county' => 'Essex','country' => 'England'],
			['county' => 'Gloucestershire','country' => 'England'],
			['county' => 'Greater London','country' => 'England'],
			['county' => 'Greater Manchester','country' => 'England'],
			['county' => 'Hampshire','country' => 'England'],
			['county' => 'Herefordshire','country' => 'England'],
			['county' => 'Hertfordshire','country' => 'England'],
			['county' => 'Isle of Wight','country' => 'England'],
			['county' => 'Isles of Scilly','country' => 'England'],
			['county' => 'Kent','country' => 'England'],
			['county' => 'Lancashire','country' => 'England'],
			['county' => 'Leicestershire','country' => 'England'],
			['county' => 'Lincolnshire','country' => 'England'],
			['county' => 'Merseyside','country' => 'England'],
			['county' => 'Norfolk','country' => 'England'],
			['county' => 'North Somerset','country' => 'England'],
			['county' => 'North Yorkshire','country' => 'England'],
			['county' => 'Northamptonshire','country' => 'England'],
			['county' => 'Northumberland','country' => 'England'],
			['county' => 'Nottinghamshire','country' => 'England'],
			['county' => 'Oxfordshire','country' => 'England'],
			['county' => 'Rutland','country' => 'England'],
			['county' => 'Shropshire','country' => 'England'],
			['county' => 'Somerset','country' => 'England'],
			['county' => 'South Gloucestershire','country' => 'England'],
			['county' => 'South Yorkshire','country' => 'England'],
			['county' => 'Staffordshire','country' => 'England'],
			['county' => 'Suffolk','country' => 'England'],
			['county' => 'Surrey','country' => 'England'],
			['county' => 'Tyne & Wear','country' => 'England'],
			['county' => 'Warwickshire','country' => 'England'],
			['county' => 'West Midlands','country' => 'England'],
			['county' => 'West Sussex','country' => 'England'],
			['county' => 'West Yorkshire','country' => 'England'],
			['county' => 'WIltshire','country' => 'England'],
			['county' => 'Worcestershire','country' => 'England'],
			['county' => 'Aberdeenshire','country' => 'Scotland'],
			['county' => 'Angus','country' => 'Scotland'],
			['county' => 'Argyll & Bute','country' => 'Scotland'],
			['county' => 'Ayrshire','country' => 'Scotland'],
			['county' => 'Banffshire','country' => 'Scotland'],
			['county' => 'Berwickshire','country' => 'Scotland'],
			['county' => 'Borders','country' => 'Scotland'],
			['county' => 'Caithness','country' => 'Scotland'],
			['county' => 'Clackmannanshire','country' => 'Scotland'],
			['county' => 'Dumfries & Galloway','country' => 'Scotland'],
			['county' => 'Dunbartonshire','country' => 'Scotland'],
			['county' => 'East Ayrshire','country' => 'Scotland'],
			['county' => 'East Dunbartonshire','country' => 'Scotland'],
			['county' => 'East Lothian','country' => 'Scotland'],
			['county' => 'East Renfrewshire','country' => 'Scotland'],
			['county' => 'Fife','country' => 'Scotland'],
			['county' => 'Highland','country' => 'Scotland'],
			['county' => 'Inverclyde','country' => 'Scotland'],
			['county' => 'Kincardineshire','country' => 'Scotland'],
			['county' => 'Midlothian','country' => 'Scotland'],
			['county' => 'Moray','country' => 'Scotland'],
			['county' => 'North Ayrshire','country' => 'Scotland'],
			['county' => 'North Lanarkshire','country' => 'Scotland'],
			['county' => 'Orkney','country' => 'Scotland'],
			['county' => 'Perth & KInross','country' => 'Scotland'],
			['county' => 'Renfrewshire','country' => 'Scotland'],
			['county' => 'Shetland','country' => 'Scotland'],
			['county' => 'South Ayrshire','country' => 'Scotland'],
			['county' => 'South Lanarkshire','country' => 'Scotland'],
			['county' => 'Stirlingshire','country' => 'Scotland'],
			['county' => 'West Dunbartonshire','country' => 'Scotland'],
			['county' => 'West Lothian','country' => 'Scotland'],
			['county' => 'Western Isles','country' => 'Scotland'],
			['county' => 'Blaenau Gwent','country' => 'Wales'],
			['county' => 'Bridgend','country' => 'Wales'],
			['county' => 'Caerphilly','country' => 'Wales'],
			['county' => 'Cardiff','country' => 'Wales'],
			['county' => 'Carmarthenshire','country' => 'Wales'],
			['county' => 'Ceredigion','country' => 'Wales'],
			['county' => 'Conwy','country' => 'Wales'],
			['county' => 'Denbighshire','country' => 'Wales'],
			['county' => 'Flintshire','country' => 'Wales'],
			['county' => 'Gwynedd','country' => 'Wales'],
			['county' => 'Isle of Anglesey','country' => 'Wales'],
			['county' => 'Merthyr Tydfil','country' => 'Wales'],
			['county' => 'Monmouthshire','country' => 'Wales'],
			['county' => 'Neath Port Talbot','country' => 'Wales'],
			['county' => 'Newport','country' => 'Wales'],
			['county' => 'Pembrokeshire','country' => 'Wales'],
			['county' => 'Powy','country' => 'Wales'],
			['county' => 'Rhondda Cynon Taff','country' => 'Wales'],
			['county' => 'Swansea','country' => 'Wales'],
			['county' => 'Torfaen','country' => 'Wales'],
			['county' => 'Vale of Glamorgan','country' => 'Wales'],
			['county' => 'Wrexham','country' => 'Wales'],
			['county' => 'Antrim','country' => 'Northern Ireland'],
			['county' => 'Armagh','country' => 'Northern Ireland'],
			['county' => 'Down','country' => 'Northern Ireland'],
			['county' => 'Fermanagh','country' => 'Northern Ireland'],
			['county' => 'Londonderry','country' => 'Northern Ireland'],
			['county' => 'Tyrone','country' => 'Northern Ireland']
		];
		
		\DB::table('counties')->insert($counties);
	}
}
