<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SkillsSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	*/
	public function run() {

		\DB::table('skills')->delete();
		\DB::table('skills')->insert([
			['name' => 'Adaptability','slug' => 'adaptability','description' => 'desc','status' => 1],
			['name' => 'Administration','slug' => 'administration','description' => 'desc','status' => 1],
			['name' => 'Analytical','slug' => 'analytical','description' => 'desc','status' => 1],
			['name' => 'Assertiveness','slug' => 'assertiveness','description' => 'desc','status' => 1],
			['name' => 'Attention to detail','slug' => 'attention_to_detail','description' => 'desc','status' => 1],
			['name' => 'Attentive','slug' => 'attentive','description' => 'desc','status' => 1],
			['name' => 'Business acumen','slug' => 'business_acumen','description' => 'desc','status' => 1],
			['name' => 'Business analysis','slug' => 'business_analysis','description' => 'desc','status' => 1],
			['name' => 'Business ethics','slug' => 'business_ethics','description' => 'desc','status' => 1],
			['name' => 'Business intelligence','slug' => 'business_intelligence','description' => 'desc','status' => 1],
			['name' => 'Business management','slug' => 'business_management','description' => 'desc','status' => 1],
			['name' => 'Business writing','slug' => 'business_writing','description' => 'desc','status' => 1],
			['name' => 'Coaching','slug' => 'coaching','description' => 'desc','status' => 1],
			['name' => 'Collaboration','slug' => 'collaboration','description' => 'desc','status' => 1],
			['name' => 'Commercial awareness','slug' => 'commercial_awareness','description' => 'desc','status' => 1],
			['name' => 'Communication','slug' => 'communication','description' => 'desc','status' => 1],
			['name' => 'Computer literacy','slug' => 'computer_literacy','description' => 'desc','status' => 1],
			['name' => 'Confidence','slug' => 'confidence','description' => 'desc','status' => 1],
			['name' => 'Conflict management','slug' => 'conflict_management','description' => 'desc','status' => 1],
			['name' => 'Conflict resolution','slug' => 'conflict_resolution','description' => 'desc','status' => 1],
			['name' => 'Consulting','slug' => 'consulting','description' => 'desc','status' => 1],
			['name' => 'Coordination','slug' => 'coordination','description' => 'desc','status' => 1],
			['name' => 'Cooperation','slug' => 'cooperation','description' => 'desc','status' => 1],
			['name' => 'Creative thinking','slug' => 'creative_thinking','description' => 'desc','status' => 1],
			['name' => 'Creativity','slug' => 'creativity','description' => 'desc','status' => 1],
			['name' => 'Critical thinking','slug' => 'critical_thinking','description' => 'desc','status' => 1],
			['name' => 'Customer care','slug' => 'customer_care','description' => 'desc','status' => 1],
			['name' => 'Customer service','slug' => 'customer_service','description' => 'desc','status' => 1],
			['name' => 'Data analysis','slug' => 'data_analysis','description' => 'desc','status' => 1],
			['name' => 'Data entry','slug' => 'data_entry','description' => 'desc','status' => 1],
			['name' => 'Data management','slug' => 'data_management','description' => 'desc','status' => 1],
			['name' => 'Debating','slug' => 'debating','description' => 'desc','status' => 1],
			['name' => 'Decision making','slug' => 'decision_making','description' => 'desc','status' => 1],
			['name' => 'Dedication','slug' => 'dedication','description' => 'desc','status' => 1],
			['name' => 'Delegation','slug' => 'delegation','description' => 'desc','status' => 1],
			['name' => 'Diplomacy','slug' => 'diplomacy','description' => 'desc','status' => 1],
			['name' => 'Disability awareness','slug' => 'disability_awareness','description' => 'desc','status' => 1],
			['name' => 'Dispute resolution','slug' => 'dispute_resolution','description' => 'desc','status' => 1],
			['name' => 'Driving licence','slug' => 'driving_licence','description' => 'desc','status' => 1],
			['name' => 'Emotional intelligence','slug' => 'emotional_intelligence','description' => 'desc','status' => 1],
			['name' => 'Energetic','slug' => 'energetic','description' => 'desc','status' => 1],
			['name' => 'Enthusiastic','slug' => 'enthusiastic','description' => 'desc','status' => 1],
			['name' => 'Entrepreneurial','slug' => 'entrepreneurial','description' => 'desc','status' => 1],
			['name' => 'Facilitator','slug' => 'facilitator','description' => 'desc','status' => 1],
			['name' => 'Flexible','slug' => 'flexible','description' => 'desc','status' => 1],
			['name' => 'Independent','slug' => 'independent','description' => 'desc','status' => 1],
			['name' => 'Innovative','slug' => 'innovative','description' => 'desc','status' => 1],
			['name' => 'Inspirational','slug' => 'inspirational','description' => 'desc','status' => 1],
			['name' => 'Intercultural','slug' => 'intercultural','description' => 'desc','status' => 1],
			['name' => 'Interpersonal communication','slug' => 'interpersonal_communication','description' => 'desc','status' => 1],
			['name' => 'IT','slug' => 'it','description' => 'desc','status' => 1],
			['name' => 'Leadership','slug' => 'leadership','description' => 'desc','status' => 1],
			['name' => 'Leadership communication','slug' => 'leadership_communication','description' => 'desc','status' => 1],
			['name' => 'Leadership development','slug' => 'leadership_development','description' => 'desc','status' => 1],
			['name' => 'Leading a team','slug' => 'leading_a_team','description' => 'desc','status' => 1],
			['name' => 'Line management','slug' => 'line_management','description' => 'desc','status' => 1],
			['name' => 'Linguistics','slug' => 'linguistics','description' => 'desc','status' => 1],
			['name' => 'Listening','slug' => 'listening','description' => 'desc','status' => 1],
			['name' => 'Literacy','slug' => 'literacy','description' => 'desc','status' => 1],
			['name' => 'Logical thinking','slug' => 'logical_thinking','description' => 'desc','status' => 1],
			['name' => 'Management','slug' => 'management','description' => 'desc','status' => 1],
			['name' => 'Management communication','slug' => 'management_communication','description' => 'desc','status' => 1],
			['name' => 'Management development','slug' => 'management_development','description' => 'desc','status' => 1],
			['name' => 'Managing a team','slug' => 'managing_a_team','description' => 'desc','status' => 1],
			['name' => 'Managing ambiguity','slug' => 'managing_ambiguity','description' => 'desc','status' => 1],
			['name' => 'Managing difficult conversations','slug' => 'managing_difficult_conversations','description' => 'desc','status' => 1],
			['name' => 'Managing remote teams','slug' => 'managing_remote_teams','description' => 'desc','status' => 1],
			['name' => 'Meeting management','slug' => 'meeting_management','description' => 'desc','status' => 1],
			['name' => 'Mentoring','slug' => 'mentoring','description' => 'desc','status' => 1],
			['name' => 'Motivated','slug' => 'motivated','description' => 'desc','status' => 1],
			['name' => 'Motivational','slug' => 'motivational','description' => 'desc','status' => 1],
			['name' => 'Multitasking','slug' => 'multitasking','description' => 'desc','status' => 1],
			['name' => 'Navigation','slug' => 'navigation','description' => 'desc','status' => 1],
			['name' => 'Negotiation','slug' => 'negotiation','description' => 'desc','status' => 1],
			['name' => 'Networking','slug' => 'networking','description' => 'desc','status' => 1],
			['name' => 'Nonverbal communication','slug' => 'nonverbal_communication','description' => 'desc','status' => 1],
			['name' => 'Note taking','slug' => 'note_taking','description' => 'desc','status' => 1],
			['name' => 'Numeracy','slug' => 'numeracy','description' => 'desc','status' => 1],
			['name' => 'Numeric','slug' => 'numeric','description' => 'desc','status' => 1],
			['name' => 'Office administration','slug' => 'office_administration','description' => 'desc','status' => 1],
			['name' => 'Organisation','slug' => 'organisation','description' => 'desc','status' => 1],
			['name' => 'Organisational','slug' => 'organisational','description' => 'desc','status' => 1],
			['name' => 'Patience','slug' => 'patience','description' => 'desc','status' => 1],
			['name' => 'People management','slug' => 'people_management','description' => 'desc','status' => 1],
			['name' => 'Perseverant','slug' => 'perseverant','description' => 'desc','status' => 1],
			['name' => 'Persistent','slug' => 'persistent','description' => 'desc','status' => 1],
			['name' => 'Personal development','slug' => 'personal_development','description' => 'desc','status' => 1],
			['name' => 'Persuasion','slug' => 'persuasion','description' => 'desc','status' => 1],
			['name' => 'Planning','slug' => 'planning','description' => 'desc','status' => 1],
			['name' => 'Presentation','slug' => 'presentation','description' => 'desc','status' => 1],
			['name' => 'Presenting','slug' => 'presenting','description' => 'desc','status' => 1],
			['name' => 'Problem-solving','slug' => 'problem-solving','description' => 'desc','status' => 1],
			['name' => 'Productivity','slug' => 'productivity','description' => 'desc','status' => 1],
			['name' => 'Project coordination','slug' => 'project_coordination','description' => 'desc','status' => 1],
			['name' => 'Project management','slug' => 'project_management','description' => 'desc','status' => 1],
			['name' => 'Proofreading','slug' => 'proofreading','description' => 'desc','status' => 1],
			['name' => 'Public speaking','slug' => 'public_speaking','description' => 'desc','status' => 1],
			['name' => 'Reading comprehension','slug' => 'reading_comprehension','description' => 'desc','status' => 1],
			['name' => 'Reasoning','slug' => 'reasoning','description' => 'desc','status' => 1],
			['name' => 'Relationship building','slug' => 'relationship_building','description' => 'desc','status' => 1],
			['name' => 'Relationship management','slug' => 'relationship_management','description' => 'desc','status' => 1],
			['name' => 'Report writing','slug' => 'report_writing','description' => 'desc','status' => 1],
			['name' => 'Research','slug' => 'research','description' => 'desc','status' => 1],
			['name' => 'Resilience','slug' => 'resilience','description' => 'desc','status' => 1],
			['name' => 'Resourceful','slug' => 'resourceful','description' => 'desc','status' => 1],
			['name' => 'Respectful','slug' => 'respectful','description' => 'desc','status' => 1],
			['name' => 'Risk management','slug' => 'risk_management','description' => 'desc','status' => 1],
			['name' => 'Self awareness','slug' => 'self_awareness','description' => 'desc','status' => 1],
			['name' => 'Self management','slug' => 'self_management','description' => 'desc','status' => 1],
			['name' => 'Self motivated','slug' => 'self_motivated','description' => 'desc','status' => 1],
			['name' => 'Sense of humour','slug' => 'sense_of_humour','description' => 'desc','status' => 1],
			['name' => 'Stakeholder management','slug' => 'stakeholder_management','description' => 'desc','status' => 1],
			['name' => 'Strategic planning','slug' => 'strategic_planning','description' => 'desc','status' => 1],
			['name' => 'Strategic thinking skills','slug' => 'strategic_thinking_skills','description' => 'desc','status' => 1],
			['name' => 'Supervising','slug' => 'supervising','description' => 'desc','status' => 1],
			['name' => 'Team building','slug' => 'team_building','description' => 'desc','status' => 1],
			['name' => 'Team leadership','slug' => 'team_leadership','description' => 'desc','status' => 1],
			['name' => 'Team management','slug' => 'team_management','description' => 'desc','status' => 1],
			['name' => 'Team player','slug' => 'team_player','description' => 'desc','status' => 1],
			['name' => 'Teamwork','slug' => 'teamwork','description' => 'desc','status' => 1],
			['name' => 'Thinking outside the box','slug' => 'thinking_outside_the_box','description' => 'desc','status' => 1],
			['name' => 'Time management','slug' => 'time_management','description' => 'desc','status' => 1],
			['name' => 'Timekeeping','slug' => 'timekeeping','description' => 'desc','status' => 1],
			['name' => 'Training','slug' => 'training','description' => 'desc','status' => 1],
			['name' => 'Troubleshooting','slug' => 'troubleshooting','description' => 'desc','status' => 1],
			['name' => 'Tutoring','slug' => 'tutoring','description' => 'desc','status' => 1],
			['name' => 'Typing','slug' => 'typing','description' => 'desc','status' => 1],
			['name' => 'Verbal communication','slug' => 'verbal_communication','description' => 'desc','status' => 1],
			['name' => 'Visual communication','slug' => 'visual_communication','description' => 'desc','status' => 1],
			['name' => 'Work ethic','slug' => 'work_ethic','description' => 'desc','status' => 1],
			['name' => 'Working under pressure','slug' => 'working_under_pressure','description' => 'desc','status' => 1],
			['name' => 'Writing','slug' => 'writing','description' => 'desc','status' => 1],
			['name' => 'Writing English','slug' => 'writing_english','description' => 'desc','status' => 1],
			['name' => 'Written communication','slug' => 'written_communication','description' => 'desc','status' => 1]
		]);
	}
}
